[config]
default_to_workspace = false

[tasks.build-no-cache]
command = "docker"
args = ["compose", "build", "--pull", "--no-cache", "--progress=plain"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-all]
command = "docker"
args = ["compose", "build"]

[tasks.nextest]
dependencies = ["build-all"]
script = """
docker compose run --rm --entrypoint "" rsrpp cargo nextest run --workspace --status-level all --test-threads=1 ${@}
"""
